"""
ASCENT Delivery — real external side-effect after Scribe completes.

Sends the executive brief to the CEO inbox via SendGrid when configured.
Falls back to structured logging in demo mode so the pipeline never blocks.
"""
from __future__ import annotations

import httpx

from backend.config import settings
from backend.models.schemas import ReportOutput
from backend.services.events import publish_event
from backend.services.logger import get_logger

logger = get_logger("delivery")

SENDGRID_URL = "https://api.sendgrid.com/v3/mail/send"


def _exec_body(report: ReportOutput) -> str:
    if report.exec_markdown:
        return report.exec_markdown
    if report.executive_summary:
        return report.executive_summary
    return (report.full_report_markdown or "")[:8000]


async def deliver_report(
    report: ReportOutput,
    *,
    workflow_id: str,
    competitor: str | None = None,
) -> dict[str, object]:
    """
    Deliver the CEO executive brief via SendGrid.

    Returns a dict with channel, success, and optional error for persistence/logging.
    """
    subject = f"[ASCENT] CEO Brief: {report.title}"
    body = _exec_body(report)
    competitor_line = competitor or "Unknown competitor"

    api_key = (settings.SENDGRID_API_KEY or "").strip()
    from_email = (settings.SENDGRID_FROM_EMAIL or "").strip()
    to_email = (settings.CEO_EMAIL or "").strip()

    if not api_key or not from_email or not to_email:
        logger.info(
            "delivery_skipped_demo",
            workflow_id=workflow_id,
            reason="SendGrid or CEO email not configured",
        )
        await publish_event("delivery.completed", {
            "workflow_id": workflow_id,
            "channel": "sendgrid",
            "success": False,
            "demo_mode": True,
            "message": "Delivery skipped (configure SENDGRID_API_KEY, SENDGRID_FROM_EMAIL, CEO_EMAIL)",
        })
        return {
            "channel": "sendgrid",
            "success": False,
            "demo_mode": True,
            "message": "SendGrid not configured — demo mode",
        }

    payload = {
        "personalizations": [{"to": [{"email": to_email}]}],
        "from": {"email": from_email, "name": "ASCENT Intelligence"},
        "subject": subject,
        "content": [
            {
                "type": "text/plain",
                "value": (
                    f"ASCENT autonomous intelligence — executive brief\n"
                    f"Workflow: {workflow_id}\n"
                    f"Competitor: {competitor_line}\n"
                    f"Confidence: {report.confidence_score:.0%}\n\n"
                    f"{'=' * 60}\n\n"
                    f"{body}\n\n"
                    f"{'=' * 60}\n"
                    f"Generated by ASCENT Scribe agent."
                ),
            }
        ],
    }

    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(
                SENDGRID_URL,
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json",
                },
                json=payload,
            )
            response.raise_for_status()

        logger.info(
            "delivery_sent",
            workflow_id=workflow_id,
            to=to_email,
            title=report.title,
        )
        await publish_event("delivery.completed", {
            "workflow_id": workflow_id,
            "channel": "sendgrid",
            "success": True,
            "message": f"CEO brief emailed to {to_email}",
        })
        return {
            "channel": "sendgrid",
            "success": True,
            "to": to_email,
            "message": f"CEO brief emailed to {to_email}",
        }

    except httpx.HTTPStatusError as exc:
        err = f"SendGrid HTTP {exc.response.status_code}: {exc.response.text[:200]}"
        logger.error("delivery_failed", workflow_id=workflow_id, error=err)
        await publish_event("delivery.completed", {
            "workflow_id": workflow_id,
            "channel": "sendgrid",
            "success": False,
            "message": err,
        })
        return {"channel": "sendgrid", "success": False, "error": err}

    except Exception as exc:
        err = str(exc)[:300]
        logger.error("delivery_failed", workflow_id=workflow_id, error=err)
        await publish_event("delivery.completed", {
            "workflow_id": workflow_id,
            "channel": "sendgrid",
            "success": False,
            "message": err,
        })
        return {"channel": "sendgrid", "success": False, "error": err}
